CREATE TABLE cidade(
  idCidade BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(50) NOT NULL,
  idEstado BIGINT(20) NOT NULL,
  FOREIGN KEY(idEstado) REFERENCES estado(idEstado)
)ENGINE=InnoDB DEFAULT CHARSET=utf8
